import {
    Activity,
    AlertCircle,
    AlertTriangle,
    Ambulance,
    ArrowLeft,
    ArrowRight,
    BarChart3,
    Bell,
    Bed,
    Beer,
    Biohazard,
    BookOpen,
    Bot,
    Building2,
    Calendar,
    Car,
    Check,
    CheckCircle2,
    ChevronDown,
    ChevronRight,
    Circle,
    CircleDot,
    ClipboardList,
    Clock,
    CloudLightning,
    Construction,
    Database,
    Droplet,
    Droplets,
    Edit,
    FileText,
    Flame,
    HelpCircle,
    Home,
    Hospital,
    Info,
    Layers,
    Lightbulb,
    LoaderCircle,
    LockKeyhole,
    LogOut,
    Landmark,
    Map,
    MapPin,
    MapPinned,
    Maximize2,
    Megaphone,
    Menu,
    Minimize2,
    MessageCircle,
    Package,
    Pause,
    Phone,
    Play,
    Plus,
    RefreshCw,
    Route,
    Ruler,
    Search,
    Send,
    ShieldCheck,
    Siren,
    Skull,
    Smile,
    Stethoscope,
    Syringe,
    Tent,
    Thermometer,
    Trash2,
    User,
    Settings,
    Users,
    Waves,
    Wifi,
    WifiOff,
    Wrench,
    X,
    XCircle
} from "lucide-react";
import { createElement } from "react";

const ICONS = {
    activity: Activity,
    alert: AlertTriangle,
    alertCircle: AlertCircle,
    ambulance: Ambulance,
    arrowLeft: ArrowLeft,
    arrowRight: ArrowRight,
    back: ArrowLeft,
    barChart: BarChart3,
    bed: Bed,
    beer: Beer,
    bell: Bell,
    biohazard: Biohazard,
    book: BookOpen,
    bot: Bot,
    building: Building2,
    calendar: Calendar,
    car: Car,
    check: Check,
    checkCircle: CheckCircle2,
    chevronDown: ChevronDown,
    chevronRight: ChevronRight,
    circle: Circle,
    circleDot: CircleDot,
    clipboard: ClipboardList,
    clock: Clock,
    cloudLightning: CloudLightning,
    construction: Construction,
    database: Database,
    disease: Biohazard,
    droplet: Droplet,
    droplets: Droplets,
    edit: Edit,
    file: FileText,
    fire: Flame,
    flood: Droplets,
    help: HelpCircle,
    home: Home,
    hospital: Hospital,
    info: Info,
    layers: Layers,
    lightbulb: Lightbulb,
    loader: LoaderCircle,
    lock: LockKeyhole,
    logout: LogOut,
    map: Map,
    mapPin: MapPin,
    mapPinned: MapPinned,
    megaphone: Megaphone,
    menu: Menu,
    message: MessageCircle,
    package: Package,
    pause: Pause,
    phone: Phone,
    play: Play,
    plus: Plus,
    refresh: RefreshCw,
    route: Route,
    ruler: Ruler,
    search: Search,
    send: Send,
    shield: ShieldCheck,
    siren: Siren,
    skull: Skull,
    smile: Smile,
    shelter: Tent,
    stethoscope: Stethoscope,
    syringe: Syringe,
    thermometer: Thermometer,
    trash: Trash2,
    user: User,
    settings: Settings,
    users: Users,
    waves: Waves,
    wifi: Wifi,
    wifiOff: WifiOff,
    wrench: Wrench,
    x: X,
    xCircle: XCircle,
    ban: XCircle,
    fullscreen: Maximize2,
    landmark: Landmark,
    minimize: Minimize2,
    tag: Info,

    "📊": BarChart3,
    "📈": BarChart3,
    "📋": ClipboardList,
    "📝": FileText,
    "📄": FileText,
    "📁": Layers,
    "📅": Calendar,
    "⏰": Clock,
    "⏱️": Clock,
    "🔢": CircleDot,
    "🔍": Search,
    "🔄": RefreshCw,
    "📞": Phone,
    "☎️": Phone,
    "📱": Phone,
    "📘": MessageCircle,
    "📢": Megaphone,
    "💬": MessageCircle,
    "💡": Lightbulb,
    "🤖": Bot,
    "👋": MessageCircle,
    "📤": Send,
    "📍": MapPin,
    "📏": Ruler,
    "📐": Ruler,
    "🗺️": Map,
    "🏠": Home,
    "🏘️": Home,
    "🏥": Hospital,
    "⛺": Tent,
    "👥": Users,
    "💧": Droplet,
    "🌊": Waves,
    "🦠": Biohazard,
    "🚗": Car,
    "🚑": Ambulance,
    "🚨": Siren,
    "🚧": Route,
    "🔥": Flame,
    "🍺": Beer,
    "⛑️": ShieldCheck,
    "😴": Clock,
    "😷": Stethoscope,
    "🚫": XCircle,
    "💉": Syringe,
    "⚡": Siren,
    "📦": Package,
    "🚰": Droplets,
    "🏃": Users,
    "🏗️": Construction,
    "💥": AlertTriangle,
    "🤕": Stethoscope,
    "🛏️": Bed,
    "🤒": Thermometer,
    "💀": Skull,
    "😊": Smile,
    "⚠️": AlertTriangle,
    "❓": HelpCircle,
    "✅": CheckCircle2,
    "❌": XCircle,
    "✕": X,
    "×": X,
    "➕": Plus,
    "✏️": Edit,
    "🗑️": Trash2,
    "🟢": Circle,
    "🔴": Circle,
    "🟡": Circle,
    "⚫": Circle,
    "⚪": Circle,
    "📡": Wifi,
    "📭": FileText,
    "🆘": Siren
};

const STATUS_COLORS = {
    "🟢": "text-green-500 fill-green-500",
    "🔴": "text-red-500 fill-red-500",
    "🟡": "text-yellow-500 fill-yellow-500",
    "⚫": "text-gray-500 fill-gray-500",
    "⚪": "text-gray-300 fill-gray-300"
};

export function getLucideIcon(icon) {
    if (!icon) return Info;
    if (typeof icon !== "string") return icon;
    return ICONS[icon] || ICONS[icon.trim()] || Info;
}

export default function AppIcon({ icon, className = "h-5 w-5", strokeWidth = 2, "aria-label": ariaLabel, ...props }) {
    const Icon = getLucideIcon(icon);
    const statusClass = typeof icon === "string" ? STATUS_COLORS[icon] || "" : "";
    return createElement(Icon, {
        "aria-hidden": ariaLabel ? undefined : true,
        "aria-label": ariaLabel,
        className: `${className} ${statusClass}`.trim(),
        strokeWidth,
        ...props
    });
}
