import {
    Activity,
    AlertCircle,
    AlertTriangle,
    Ambulance,
    Accessibility,
    ArrowLeft,
    ArrowRight,
    ArrowUp,
    BarChart3,
    Bell,
    Bed,
    Beer,
    Biohazard,
    BookOpen,
    Bot,
    BriefcaseBusiness,
    Building2,
    Cable,
    Calendar,
    CalendarDays,
    Camera,
    Car,
    Check,
    CheckCircle2,
    ChevronDown,
    ChevronRight,
    Circle,
    CircleDot,
    CirclePause,
    CirclePlay,
    ClipboardList,
    Clock,
    CloudLightning,
    Construction,
    Database,
    Droplet,
    Droplets,
    Edit,
    Earth,
    FileText,
    Flame,
    HelpCircle,
    Home,
    Hospital,
    Info,
    Layers,
    Link,
    Lightbulb,
    LoaderCircle,
    LockKeyhole,
    LogOut,
    Landmark,
    Map,
    MapPin,
    MapPinned,
    Maximize2,
    Megaphone,
    Menu,
    Minimize2,
    MessageCircle,
    Package,
    PartyPopper,
    Pause,
    PersonStanding,
    PieChart,
    Pill,
    Phone,
    Play,
    Plus,
    RefreshCw,
    Route,
    Ruler,
    Search,
    Send,
    Save,
    ShieldCheck,
    Siren,
    Skull,
    Smile,
    Stethoscope,
    Syringe,
    Tent,
    TentTree,
    Thermometer,
    Timer,
    TrendingDown,
    Trash2,
    User,
    UserRoundCog,
    Settings,
    Users,
    Waves,
    Wifi,
    WifiOff,
    Wrench,
    Mail,
    Monitor,
    Baby,
    Cloud,
    HardHat,
    House,
    Pin,
    Rocket,
    Sun,
    Tag,
    TreePalm,
    ChevronLeft,
    ChevronUp,
    X,
    XCircle
} from "lucide-react";
import { createElement } from "react";

const ICONS = {
    activity: Activity,
    accessibility: Accessibility,
    alert: AlertTriangle,
    alertCircle: AlertCircle,
    ambulance: Ambulance,
    arrowLeft: ArrowLeft,
    arrowRight: ArrowRight,
    arrowUp: ArrowUp,
    back: ArrowLeft,
    barChart: BarChart3,
    bed: Bed,
    beer: Beer,
    bell: Bell,
    biohazard: Biohazard,
    book: BookOpen,
    bot: Bot,
    briefcase: BriefcaseBusiness,
    building: Building2,
    calendar: Calendar,
    calendarDays: CalendarDays,
    camera: Camera,
    car: Car,
    check: Check,
    checkCircle: CheckCircle2,
    chevronDown: ChevronDown,
    chevronRight: ChevronRight,
    circle: Circle,
    statusGreen: Circle,
    statusRed: Circle,
    statusYellow: Circle,
    statusBlack: Circle,
    statusGray: Circle,
    statusBlue: Circle,
    statusOrange: Circle,
    statusPurple: Circle,
    circleDot: CircleDot,
    circlePause: CirclePause,
    circlePlay: CirclePlay,
    clipboard: ClipboardList,
    clock: Clock,
    cloudLightning: CloudLightning,
    construction: Construction,
    database: Database,
    earth: Earth,
    disease: Biohazard,
    droplet: Droplet,
    droplets: Droplets,
    edit: Edit,
    file: FileText,
    fire: Flame,
    flood: Droplets,
    help: HelpCircle,
    home: Home,
    hospital: Hospital,
    info: Info,
    layers: Layers,
    link: Link,
    lightbulb: Lightbulb,
    loader: LoaderCircle,
    lock: LockKeyhole,
    logout: LogOut,
    map: Map,
    mapPin: MapPin,
    mapPinned: MapPinned,
    megaphone: Megaphone,
    menu: Menu,
    message: MessageCircle,
    package: Package,
    party: PartyPopper,
    personStanding: PersonStanding,
    pieChart: PieChart,
    pill: Pill,
    pause: Pause,
    phone: Phone,
    play: Play,
    plus: Plus,
    refresh: RefreshCw,
    route: Route,
    ruler: Ruler,
    search: Search,
    send: Send,
    save: Save,
    shield: ShieldCheck,
    siren: Siren,
    skull: Skull,
    smile: Smile,
    shelter: Tent,
    stethoscope: Stethoscope,
    syringe: Syringe,
    thermometer: Thermometer,
    timer: Timer,
    trendingDown: TrendingDown,
    trash: Trash2,
    user: User,
    userCog: UserRoundCog,
    settings: Settings,
    users: Users,
    waves: Waves,
    wifi: Wifi,
    wifiOff: WifiOff,
    wrench: Wrench,
    mail: Mail,
    monitor: Monitor,
    baby: Baby,
    cable: Cable,
    cloud: Cloud,
    hardHat: HardHat,
    house: House,
    pin: Pin,
    rocket: Rocket,
    sun: Sun,
    tag: Tag,
    tentTree: TentTree,
    treePalm: TreePalm,
    chevronLeft: ChevronLeft,
    chevronUp: ChevronUp,
    x: X,
    xCircle: XCircle,
    ban: XCircle,
    fullscreen: Maximize2,
    landmark: Landmark,
    minimize: Minimize2,
    tag: Tag,

    "📊": BarChart3,
    "📈": BarChart3,
    "📋": ClipboardList,
    "📝": FileText,
    "📄": FileText,
    "📁": Layers,
    "📅": Calendar,
    "⏰": Clock,
    "⏱️": Clock,
    "🔢": CircleDot,
    "🔍": Search,
    "🔄": RefreshCw,
    "📞": Phone,
    "☎️": Phone,
    "📱": Phone,
    "📧": Mail,
    "📥": ArrowLeft,
    "📘": MessageCircle,
    "📢": Megaphone,
    "💬": MessageCircle,
    "💡": Lightbulb,
    "🤖": Bot,
    "👋": MessageCircle,
    "📤": Send,
    "📍": MapPin,
    "📏": Ruler,
    "📐": Ruler,
    "🗺️": Map,
    "🏠": Home,
    "🏡": House,
    "🏘️": Home,
    "🏚️": House,
    "🏛️": Landmark,
    "🏢": Building2,
    "🏕️": TentTree,
    "🏥": Hospital,
    "⛺": Tent,
    "👥": Users,
    "👤": User,
    "👨‍💼": UserRoundCog,
    "👨‍👩‍👧‍👦": Users,
    "👮": ShieldCheck,
    "👴": User,
    "👶": Baby,
    "🧍": PersonStanding,
    "🧑‍🦽": Accessibility,
    "♿": Accessibility,
    "🤰": Accessibility,
    "💧": Droplet,
    "💦": Droplets,
    "🌊": Waves,
    "🦠": Biohazard,
    "🚗": Car,
    "🚔": Car,
    "🚀": Rocket,
    "🚑": Ambulance,
    "🚨": Siren,
    "🚧": Route,
    "🔥": Flame,
    "🍺": Beer,
    "💊": Pill,
    "⛑️": ShieldCheck,
    "😴": Clock,
    "😷": Stethoscope,
    "🚫": XCircle,
    "💉": Syringe,
    "⚡": Siren,
    "💻": Monitor,
    "🖥️": Monitor,
    "🌐": Earth,
    "🌍": Earth,
    "📦": Package,
    "🚰": Droplets,
    "🏃": Users,
    "🏗️": Construction,
    "🌵": TreePalm,
    "☁": Cloud,
    "☀️": Sun,
    "💥": AlertTriangle,
    "🤕": Stethoscope,
    "🛏️": Bed,
    "🤒": Thermometer,
    "💀": Skull,
    "😊": Smile,
    "⏳": Timer,
    "🕐": Clock,
    "⚠️": AlertTriangle,
    "❓": HelpCircle,
    "✅": CheckCircle2,
    "❌": XCircle,
    "✕": X,
    "×": X,
    "➕": Plus,
    "✏️": Edit,
    "🗑️": Trash2,
    "💾": Save,
    "⚙️": Settings,
    "🔐": LockKeyhole,
    "🔒": LockKeyhole,
    "🎭": UserRoundCog,
    "💼": BriefcaseBusiness,
    "📸": Camera,
    "🔗": Link,
    "📚": BookOpen,
    "🏷️": Tag,
    "📌": Pin,
    "📉": TrendingDown,
    "🎉": PartyPopper,
    "🎄": TreePalm,
    "🥧": PieChart,
    "🪢": ShieldCheck,
    "🪦": Skull,
    "🔧": Wrench,
    "🔔": Bell,
    "🎨": Layers,
    "🔌": Cable,
    "⬆️": ArrowUp,
    "▶️": CirclePlay,
    "▶": CirclePlay,
    "⏸️": CirclePause,
    "🔼": ChevronUp,
    "◀️": ChevronLeft,
    "🗓️": CalendarDays,
    "📆": CalendarDays,
    "🟢": Circle,
    "🔴": Circle,
    "🟡": Circle,
    "⚫": Circle,
    "⚪": Circle,
    "🔵": Circle,
    "🟠": Circle,
    "🟣": Circle,
    "📡": Wifi,
    "📭": FileText,
    "🆘": Siren
};

const STATUS_COLORS = {
    "🟢": "text-green-500 fill-green-500",
    "🔴": "text-red-500 fill-red-500",
    "🟡": "text-yellow-500 fill-yellow-500",
    "⚫": "text-gray-500 fill-gray-500",
    "⚪": "text-gray-300 fill-gray-300",
    "🔵": "text-blue-500 fill-blue-500",
    "🟠": "text-orange-500 fill-orange-500",
    "🟣": "text-purple-500 fill-purple-500",
    statusGreen: "text-green-500 fill-green-500",
    statusRed: "text-red-500 fill-red-500",
    statusYellow: "text-yellow-500 fill-yellow-500",
    statusBlack: "text-gray-500 fill-gray-500",
    statusGray: "text-gray-300 fill-gray-300",
    statusBlue: "text-blue-500 fill-blue-500",
    statusOrange: "text-orange-500 fill-orange-500",
    statusPurple: "text-purple-500 fill-purple-500"
};

export function getLucideIcon(icon) {
    if (!icon) return Info;
    if (typeof icon !== "string") return icon;
    return ICONS[icon] || ICONS[icon.trim()] || Info;
}

export default function AppIcon({ icon, className = "h-5 w-5", strokeWidth = 2, "aria-label": ariaLabel, ...props }) {
    const Icon = getLucideIcon(icon);
    const statusClass = typeof icon === "string" ? STATUS_COLORS[icon] || "" : "";
    return createElement(Icon, {
        "aria-hidden": ariaLabel ? undefined : true,
        "aria-label": ariaLabel,
        className: `${className} ${statusClass}`.trim(),
        strokeWidth,
        ...props
    });
}
