-- สร้างตาราง flood_records สำหรับบันทึกพื้นที่น้ำท่วม
CREATE TABLE IF NOT EXISTS flood_records (
    id INT AUTO_INCREMENT PRIMARY KEY,
    year INT NOT NULL COMMENT 'ปีที่เกิดน้ำท่วม',
    polygon_id INT NULL COMMENT 'FK to satun_village_polygon',
    province VARCHAR(100) DEFAULT 'สตูล' COMMENT 'จังหวัด',
    district VARCHAR(100) NOT NULL COMMENT 'อำเภอ',
    tambon VARCHAR(100) NOT NULL COMMENT 'ตำบล',
    village VARCHAR(100) NULL COMMENT 'หมู่บ้าน',
    flood_level ENUM('ไม่มี', 'ต่ำ', 'ปานกลาง', 'สูง', 'สูงมาก') DEFAULT 'ไม่มี' COMMENT 'ระดับน้ำท่วม',
    flood_start_date DATE NULL COMMENT 'วันที่เริ่มน้ำท่วม',
    flood_end_date DATE NULL COMMENT 'วันที่น้ำลด (ไม่ใช้งาน)',
    water_depth_cm DECIMAL(10,2) NULL COMMENT 'ความลึกของน้ำ (เซนติเมตร)',
    affected_area_sqm DECIMAL(15,2) NULL COMMENT 'พื้นที่ได้รับผลกระทบ (ตารางเมตร)',
    affected_households INT DEFAULT 0 COMMENT 'จำนวนครัวเรือนที่ได้รับผลกระทบ',
    affected_people INT DEFAULT 0 COMMENT 'จำนวนประชากรที่ได้รับผลกระทบ',
    description TEXT NULL COMMENT 'รายละเอียดเพิ่มเติม',
    damage_amount DECIMAL(15,2) DEFAULT 0 COMMENT 'มูลค่าความเสียหาย (บาท) - ไม่ใช้งาน',
    relief_amount DECIMAL(15,2) DEFAULT 0 COMMENT 'งบประมาณช่วยเหลือ (บาท) - ไม่ใช้งาน',
    status VARCHAR(50) DEFAULT 'กำลังดำเนินการ' COMMENT 'สถานะ - ไม่ใช้งาน',
    created_by VARCHAR(100) NULL COMMENT 'ผู้บันทึก',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT 'วันที่บันทึก',
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'วันที่แก้ไขล่าสุด',
    
    INDEX idx_year (year),
    INDEX idx_district (district),
    INDEX idx_tambon (tambon),
    INDEX idx_flood_level (flood_level),
    INDEX idx_polygon (polygon_id),
    FOREIGN KEY (polygon_id) REFERENCES satun_village_polygon(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='บันทึกพื้นที่น้ำท่วม';
