-- สร้างตารางสำหรับเก็บข้อมูลหมู่บ้านสตูล
CREATE TABLE IF NOT EXISTS satun_village_polygon (
    id INT AUTO_INCREMENT PRIMARY KEY,
    fid INT,
    area_name VARCHAR(255),
    regname VARCHAR(100),
    num_hh INT,
    villcode VARCHAR(50),
    num_build INT,
    distname VARCHAR(100),
    ea_code_15 VARCHAR(50),
    subdistnam VARCHAR(100),
    area_type INT,
    areacode INT,
    provname VARCHAR(100),
    mun_tao_na VARCHAR(255),
    provcode VARCHAR(10),
    villname VARCHAR(100),
    regcode INT,
    ea_no VARCHAR(50),
    muntaocode VARCHAR(50),
    shape_length DOUBLE,
    shape_area DOUBLE,
    geom GEOMETRY NOT NULL,
    SPATIAL INDEX(geom)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
