version: '3.8'

services:
  # ส่วนของ Database
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} # เปลี่ยนรหัสผ่านตรงนี้
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  # ส่วนของ phpMyAdmin
  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_HOST=${PMA_HOST}  # ชื่อ Service ของตัว database ด้านบน
      - UPLOAD_LIMIT=${UPLOAD_LIMIT}
      - PMA_PORT=${PMA_PORT}
    depends_on:
      - db

volumes:
  db_data: