services:
  # 1. Database Container
  db:
    image: mysql:8.0
    container_name: stn-eoc-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - db_data:/var/lib/mysql  # เก็บข้อมูลไว้ใน Volume กันข้อมูลหายเมื่อลบ Container

  # 2. Next.js App Container
  stn-eoc-app:
    build: .
    container_name: stn-eoc-app
    restart: always
    depends_on:
      - db  # รอให้ Database รันก่อนค่อยรัน App
    environment:
      - DB_HOST=db  # ใช้ชื่อ service 'db' แทน IP
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - DB_NAME=${MYSQL_DATABASE}
      - DATABASE_URL=mysql://root:${MYSQL_ROOT_PASSWORD}@db:3306/${MYSQL_DATABASE}
      - UPLOAD_DIR=/app/public/uploads
      - NEXT_PUBLIC_BASE_PATH=${NEXT_PUBLIC_BASE_PATH}
      - NODE_ENV=${NODE_ENV}

    ports:
      - "0.0.0.0:3001:3000"
    volumes:
      - uploads_data:/app/public/uploads  # เก็บไฟล์ที่อัปโหลดไว้ถาวรและให้ route เสิร์ฟจาก volume เดียวกัน
volumes:
  db_data:
  uploads_data: