CREATE TABLE IF NOT EXISTS villages (
    id SERIAL PRIMARY KEY,
    amphoe VARCHAR(255),
    tambon VARCHAR(255),
    moo VARCHAR(10),
    village_name VARCHAR(255)
);
TRUNCATE TABLE villages;
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ละงู', 'กำแพง', '1', 'ควนไสน');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ละงู', 'กำแพง', '2', 'ท่าแลหลา');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ละงู', 'กำแพง', '3', 'ควน');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ละงู', 'กำแพง', '4', 'ควนใหญ่');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ละงู', 'กำแพง', '5', 'ปิใหญ่');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ละงู', 'กำแพง', '6', 'ปลักมาลัย');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ละงู', 'กำแพง', '7', 'โกตา');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ละงู', 'กำแพง', '8', 'อุไร');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ละงู', 'กำแพง', '9', 'ป่าฝาง');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ละงู', 'กำแพง', '10', 'ปากปิง');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ละงู', 'กำแพง', '11', 'ทุ่งเสม็ด');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ละงู', 'กำแพง', '12', 'ตูแตหรำ');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ละงู', 'กำแพง', '0', 'กำแพง');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ละงู', 'กำแพง', '3', 'ควน');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ละงู', 'กำแพง', '4', 'ควนใหญ่');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ละงู', 'ละงู', '0', 'ละงู');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ละงู', 'ละงู', '1', 'ท่าชะมวง');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ละงู', 'ละงู', '2', 'ปากละงู');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ละงู', 'ละงู', '3', 'เกาะยวน');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ละงู', 'ละงู', '4', 'ลาหงา');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ละงู', 'ละงู', '5', 'ทุ่ง');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ละงู', 'ละงู', '6', 'หัวทาง');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ละงู', 'ละงู', '7', 'บากันโต๊ะทิด');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ละงู', 'ละงู', '8', 'นาพญา');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ละงู', 'ละงู', '9', 'คลองขุด');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ละงู', 'ละงู', '10', 'ห้วยไทร');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ละงู', 'ละงู', '11', 'ห้วยมะพร้าว');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ละงู', 'ละงู', '12', 'ในเมือง');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ละงู', 'ละงู', '13', 'ทุ่งพัฒนา');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ละงู', 'ละงู', '14', 'หลอมปืน');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ละงู', 'ละงู', '15', 'ในใส');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ละงู', 'ละงู', '16', 'คลองน้ำเค็ม');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ละงู', 'ละงู', '17', 'วังช่อนชัย');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ละงู', 'ละงู', '18', 'โคกพยอม');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ละงู', 'เขาขาว', '1', 'สันติสุข');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ละงู', 'เขาขาว', '2', 'หาญ');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ละงู', 'เขาขาว', '3', 'บ่อหิน');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ละงู', 'เขาขาว', '4', 'นาข่าเหนือ');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ละงู', 'เขาขาว', '5', 'ดาหลำ');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ละงู', 'เขาขาว', '6', 'ทุ่งเกาะปราบ');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ละงู', 'เขาขาว', '7', 'นาข่าใต้');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ละงู', 'ปากน้ำ', '1', 'บ่อเจ็ดลูก');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ละงู', 'ปากน้ำ', '2', 'ปากบารา');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ละงู', 'ปากน้ำ', '3', 'เกาะบุโหลน');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ละงู', 'ปากน้ำ', '4', 'ตะโละใส');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ละงู', 'ปากน้ำ', '5', 'ท่ายาง');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ละงู', 'ปากน้ำ', '6', 'ท่ามาลัย');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ละงู', 'ปากน้ำ', '7', 'ท่าพยอม');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ละงู', 'น้ำผุด', '1', 'ทุ่งไหม้');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ละงู', 'น้ำผุด', '2', 'หัวควน');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ละงู', 'น้ำผุด', '3', 'เกาะเปลว');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ละงู', 'น้ำผุด', '4', 'วังสายทอง');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ละงู', 'น้ำผุด', '5', 'ทุ่งนาแก้ว');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ละงู', 'น้ำผุด', '6', 'หนองราโพธิ์');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ละงู', 'น้ำผุด', '7', 'ลานเสือ');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ละงู', 'น้ำผุด', '8', 'หนองยูง');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ละงู', 'น้ำผุด', '9', 'หนองหอยโข่ง');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ละงู', 'น้ำผุด', '10', 'วังนาใน');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ละงู', 'น้ำผุด', '11', 'วังยาว');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ละงู', 'แหลมสน', '1', 'ตันหยงละไน้');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ละงู', 'แหลมสน', '2', 'กาแบง');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ละงู', 'แหลมสน', '3', 'บุโบย');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ละงู', 'แหลมสน', '4', 'สนกลาง');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ละงู', 'แหลมสน', '5', 'สุไหงมุโซะ');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ละงู', 'แหลมสน', '6', 'สนใหม่');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ทุ่งหว้า', 'ทุ่งหว้า', '0', 'ทุ่งหว้า');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ทุ่งหว้า', 'ทุ่งหว้า', '4', 'ทุ่งปรือ');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ทุ่งหว้า', 'ทุ่งหว้า', '5', 'ท่าขาม');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ทุ่งหว้า', 'ทุ่งหว้า', '7', 'คีรีวง');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ทุ่งหว้า', 'ทุ่งหว้า', '8', 'ควนตำเสา');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ทุ่งหว้า', 'ทุ่งหว้า', '9', 'ราวปลา');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ทุ่งหว้า', 'ทุ่งหว้า', '10', 'ธารปลิว');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ทุ่งหว้า', 'ทุ่งหว้า', '0', 'ทุ่งหว้า');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ทุ่งหว้า', 'ทุ่งหว้า', '1', 'ท่าอ้อย');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ทุ่งหว้า', 'ทุ่งหว้า', '2', 'ท่าเรือ');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ทุ่งหว้า', 'ทุ่งหว้า', '3', 'ในบ้าน');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ทุ่งหว้า', 'ทุ่งหว้า', '4', 'ทุ่งปรือ');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ทุ่งหว้า', 'ทุ่งหว้า', '6', 'โพธิ์');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ทุ่งหว้า', 'นาทอน', '1', 'นาทอน');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ทุ่งหว้า', 'นาทอน', '2', 'นากลาง');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ทุ่งหว้า', 'นาทอน', '3', 'ช่องไทร');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ทุ่งหว้า', 'นาทอน', '4', 'วังตง');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ทุ่งหว้า', 'นาทอน', '5', 'ท่าศิลา');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ทุ่งหว้า', 'นาทอน', '6', 'ท่าข้ามควาย');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ทุ่งหว้า', 'นาทอน', '7', 'บารายี');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ทุ่งหว้า', 'นาทอน', '8', 'ทุ่งใหญ่');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ทุ่งหว้า', 'นาทอน', '9', 'วังเจริญราษฎร์');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ทุ่งหว้า', 'ขอนคลาน', '1', 'ขอนคลานตะวันออก');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ทุ่งหว้า', 'ขอนคลาน', '2', 'ราไวใต้');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ทุ่งหว้า', 'ขอนคลาน', '3', 'ขอนคลานตะวันตก');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ทุ่งหว้า', 'ขอนคลาน', '4', 'ราไวเหนือ');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ทุ่งหว้า', 'ทุ่งบุหลัง', '1', 'มะหงัง');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ทุ่งหว้า', 'ทุ่งบุหลัง', '2', 'ทุ่งสะโบ๊ะ');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ทุ่งหว้า', 'ทุ่งบุหลัง', '3', 'ทุ่งทะนาน');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ทุ่งหว้า', 'ทุ่งบุหลัง', '4', 'ท่านา');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ทุ่งหว้า', 'ทุ่งบุหลัง', '5', 'ทุ่งบุหลัง');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ทุ่งหว้า', 'ป่าแก่บ่อหิน', '1', 'ป่าแก่บ่อหิน');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ทุ่งหว้า', 'ป่าแก่บ่อหิน', '2', 'ห้วยบ่า');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ทุ่งหว้า', 'ป่าแก่บ่อหิน', '3', 'ทุ่งดินลุ่ม');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ทุ่งหว้า', 'ป่าแก่บ่อหิน', '4', 'ขุมทรัพย์');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ทุ่งหว้า', 'ป่าแก่บ่อหิน', '5', 'สะพานวา');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ทุ่งหว้า', 'ป่าแก่บ่อหิน', '6', 'ทุ่งขมิ้น');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ทุ่งหว้า', 'ป่าแก่บ่อหิน', '7', 'เขาแดง');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ควนกาหลง', 'ทุ่งนุ้ย', '1', 'ทุ่งตำเสา');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ควนกาหลง', 'ทุ่งนุ้ย', '2', 'ทุ่งนุ้ย');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ควนกาหลง', 'ทุ่งนุ้ย', '3', 'หัวกาหมิง');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ควนกาหลง', 'ทุ่งนุ้ย', '4', 'น้ำร้อน');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ควนกาหลง', 'ทุ่งนุ้ย', '5', 'ป้านโตน');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ควนกาหลง', 'ทุ่งนุ้ย', '6', 'น้ำหรา');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ควนกาหลง', 'ทุ่งนุ้ย', '7', 'เกาะใหญ่');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ควนกาหลง', 'ทุ่งนุ้ย', '8', 'ค่ายรวมมิตร');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ควนกาหลง', 'ทุ่งนุ้ย', '9', 'ทุ่งพัก');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ควนกาหลง', 'ทุ่งนุ้ย', '10', 'ควนเรือ');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ควนกาหลง', 'ทุ่งนุ้ย', '11', 'สวน');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ควนกาหลง', 'ทุ่งนุ้ย', '12', 'โคกโดน');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ควนกาหลง', 'ควนกาหลง', '0', 'ควนกาหลง');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ควนกาหลง', 'ควนกาหลง', '1', 'ห้วยน้ำดำ');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ควนกาหลง', 'ควนกาหลง', '2', 'ซอย 10');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ควนกาหลง', 'ควนกาหลง', '3', 'ซอยสาม');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ควนกาหลง', 'ควนกาหลง', '4', 'ซอย 4');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ควนกาหลง', 'ควนกาหลง', '5', 'พรุ');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ควนกาหลง', 'ควนกาหลง', '6', 'เขาใคร');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ควนกาหลง', 'ควนกาหลง', '7', 'ซอย 8');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ควนกาหลง', 'ควนกาหลง', '8', 'เหนือคลอง');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ควนกาหลง', 'ควนกาหลง', '9', 'วังผาสามัคคี');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ควนกาหลง', 'ควนกาหลง', '10', 'ห้วยน้ำดำใน');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ควนกาหลง', 'ควนกาหลง', '11', 'ปาล์มไทย');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ควนกาหลง', 'อุใดเจริญ', '1', 'ผัง 1');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ควนกาหลง', 'อุใดเจริญ', '2', 'ผัง 32,34,39');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ควนกาหลง', 'อุใดเจริญ', '3', 'ผัง 35');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ควนกาหลง', 'อุใดเจริญ', '4', 'ผัง 3,121');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ควนกาหลง', 'อุใดเจริญ', '5', 'อุใดใต้');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ควนกาหลง', 'อุใดเจริญ', '6', 'อุใดเจริญ(ไร่สาธิต)');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ควนกาหลง', 'อุใดเจริญ', '7', 'ผัง 119,120');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ควนกาหลง', 'อุใดเจริญ', '8', 'ผัง 42');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ควนกาหลง', 'อุใดเจริญ', '9', 'ผัง 4');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('เมืองสตูล', 'พิมาน', '0', 'พิมาน');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('เมืองสตูล', 'คลองขุด', '1', 'เขาจีน');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('เมืองสตูล', 'คลองขุด', '2', 'ท่าจีน');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('เมืองสตูล', 'คลองขุด', '3', 'เกาะนก');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('เมืองสตูล', 'คลองขุด', '4', 'คลองขุด');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('เมืองสตูล', 'คลองขุด', '5', 'นาแค');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('เมืองสตูล', 'คลองขุด', '6', 'วัดหน้าเมือง');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('เมืองสตูล', 'คลองขุด', '7', 'คลองขุดเหนือ');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('เมืองสตูล', 'ควนขัน', '1', 'ควนดินแดง');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('เมืองสตูล', 'ควนขัน', '2', 'กะดุ');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('เมืองสตูล', 'ควนขัน', '3', 'นาลาน');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('เมืองสตูล', 'ควนขัน', '4', 'ไทรงาม');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('เมืองสตูล', 'ควนขัน', '5', 'เนินสูง บ้านแรกอด บ้านควนขัน');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('เมืองสตูล', 'ควนขัน', '6', 'ท่าหิน');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('เมืองสตูล', 'บ้านควน', '1', 'โต๊ะเดาะ บ้านกาเนะ');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('เมืองสตูล', 'บ้านควน', '2', 'ทุ่งวิมาน');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('เมืองสตูล', 'บ้านควน', '3', 'โคกทราย');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('เมืองสตูล', 'บ้านควน', '4', 'คลองตาย');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('เมืองสตูล', 'บ้านควน', '5', 'ควน');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('เมืองสตูล', 'บ้านควน', '6', 'กาลูบี');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('เมืองสตูล', 'บ้านควน', '7', 'ลูโบ๊ะกา.รายี');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('เมืองสตูล', 'ฉลุง', '1', 'ฉลุงใต้');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('เมืองสตูล', 'ฉลุง', '2', 'จีน');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('เมืองสตูล', 'ฉลุง', '3', 'ท่าคลองใต้');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('เมืองสตูล', 'ฉลุง', '4', 'ท่าคลอง');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('เมืองสตูล', 'ฉลุง', '5', 'โต๊ะยูด๊ะ');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('เมืองสตูล', 'ฉลุง', '6', 'กุบังจามังใต้');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('เมืองสตูล', 'ฉลุง', '7', 'กุบังจามังเหนือ');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('เมืองสตูล', 'ฉลุง', '8', 'ทุ่ง');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('เมืองสตูล', 'ฉลุง', '9', 'หัวเขา');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('เมืองสตูล', 'ฉลุง', '10', 'โต๊ะวัง');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('เมืองสตูล', 'ฉลุง', '11', 'โคกประดู่');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('เมืองสตูล', 'ฉลุง', '12', 'เขาน้อย');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('เมืองสตูล', 'ฉลุง', '13', 'ริมห้วย');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('เมืองสตูล', 'ฉลุง', '14', 'ทุ่งพญา');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('เมืองสตูล', 'ฉลุง', '1', 'ฉลุงใต้');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('เมืองสตูล', 'ฉลุง', '2', 'จีน');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('เมืองสตูล', 'ฉลุง', '5', 'โต๊ะยูด๊ะ');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('เมืองสตูล', 'ฉลุง', '13', 'ริมห้วย');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('เมืองสตูล', 'เกาะสาหร่าย', '1', 'ตันหยงอุมา');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('เมืองสตูล', 'เกาะสาหร่าย', '2', 'บากันใหญ่พัฒนา');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('เมืองสตูล', 'เกาะสาหร่าย', '3', 'ตันหยงกลิง');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('เมืองสตูล', 'เกาะสาหร่าย', '4', 'ยะระโตดนุ้ย');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('เมืองสตูล', 'เกาะสาหร่าย', '5', 'เกาะสาหร่าย (ยะระโตดใหญ่)');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('เมืองสตูล', 'เกาะสาหร่าย', '6', 'ตะโล๊ะน้ำ');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('เมืองสตูล', 'เกาะสาหร่าย', '7', 'เกาะอาดัง (เกาะลีเป๊ะ)');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('เมืองสตูล', 'เกาะสาหร่าย', '8', 'หลีเป๊ะพัฒนา');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('เมืองสตูล', 'เจ๊ะบิลัง', '1', 'ฉลุง');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('เมืองสตูล', 'เจ๊ะบิลัง', '2', 'เจ๊ะบิลัง');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('เมืองสตูล', 'เจ๊ะบิลัง', '3', 'ปาเต๊ะ');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('เมืองสตูล', 'เจ๊ะบิลัง', '4', 'โต๊ะกุกี');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('เมืองสตูล', 'เจ๊ะบิลัง', '5', 'กาลันยินตัน บ้านลุ่มหว้า');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('เมืองสตูล', 'เจ๊ะบิลัง', '6', 'ปาเต๊ะเหนือ');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('เมืองสตูล', 'เจ๊ะบิลัง', '2', 'เจ๊ะบิลัง');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('เมืองสตูล', 'ตันหยงโป', '1', 'ตันหยงโป');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('เมืองสตูล', 'ตันหยงโป', '2', 'หาดทรายยาว');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('เมืองสตูล', 'ตันหยงโป', '3', 'บากันเคย');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('เมืองสตูล', 'ตำมะลัง', '1', 'กาลันบาตู');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('เมืองสตูล', 'ตำมะลัง', '2', 'ตำมะลังเหนือ');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('เมืองสตูล', 'ตำมะลัง', '3', 'ตำมะลังใต้');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('เมืองสตูล', 'ปูยู', '1', 'เกาะยาว');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('เมืองสตูล', 'ปูยู', '2', 'ตันหยงกาโบย');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('เมืองสตูล', 'ปูยู', '3', 'ปูยู');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('เมืองสตูล', 'ควนโพธิ์', '1', 'เขาน้อยตก');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('เมืองสตูล', 'ควนโพธิ์', '2', 'ควนโพธิ์');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('เมืองสตูล', 'ควนโพธิ์', '3', 'โคกพิลา');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('เมืองสตูล', 'ควนโพธิ์', '4', 'เกาะเนียง');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('เมืองสตูล', 'ควนโพธิ์', '5', 'ใหม่');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('เมืองสตูล', 'ควนโพธิ์', '6', 'ห้วยลึก');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('เมืองสตูล', 'ควนโพธิ์', '7', 'โคกไคร');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('เมืองสตูล', 'เกตรี', '1', 'ไร่');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('เมืองสตูล', 'เกตรี', '2', 'กาเน๊ะ');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('เมืองสตูล', 'เกตรี', '3', 'เกตรี');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('เมืองสตูล', 'เกตรี', '4', 'ลูโป๊ะฆอเลาะ');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('เมืองสตูล', 'เกตรี', '5', 'วังพะเนียด');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('เมืองสตูล', 'เกตรี', '6', 'โคกมุดพัฒนา');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('เมืองสตูล', 'เกตรี', '7', 'ทุ่ง');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ท่าแพ', 'ท่าแพ', '1', 'ท่าน้ำเค็มใต้');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ท่าแพ', 'ท่าแพ', '2', 'ท่าแพกลาง');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ท่าแพ', 'ท่าแพ', '3', 'มุด');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ท่าแพ', 'ท่าแพ', '4', 'ปลักหว้า');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ท่าแพ', 'ท่าแพ', '5', 'ควนโต๊ะเจ๊ะ');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ท่าแพ', 'ท่าแพ', '6', 'ท่าแพใต้');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ท่าแพ', 'ท่าแพ', '7', 'สายควน');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ท่าแพ', 'ท่าแพ', '8', 'ดาหลำ');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ท่าแพ', 'ท่าแพ', '9', 'นาแก้ว');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ท่าแพ', 'ท่าแพ', '10', 'ควนบิหลายสา');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ท่าแพ', 'แป-ระ', '1', 'ควนเก');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ท่าแพ', 'แป-ระ', '2', 'ควนโต๊ะ');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ท่าแพ', 'แป-ระ', '3', 'เกาะไทร');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ท่าแพ', 'แป-ระ', '4', 'แป-ระเหนือ');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ท่าแพ', 'แป-ระ', '5', 'สวนเทศ');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ท่าแพ', 'แป-ระ', '6', 'นาโต๊ะขุน');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ท่าแพ', 'แป-ระ', '7', 'สวนไทย');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ท่าแพ', 'สาคร', '1', 'ทุ่งริ้น');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ท่าแพ', 'สาคร', '2', 'สาคร');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ท่าแพ', 'สาคร', '3', 'คลองลิกี');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ท่าแพ', 'สาคร', '4', 'ตื่น');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ท่าแพ', 'สาคร', '5', 'ปลักแรด');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ท่าแพ', 'สาคร', '6', 'คลองบัน');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ท่าแพ', 'สาคร', '7', 'ทางยาง');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ท่าแพ', 'สาคร', '8', 'คลองสองปาก');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ท่าแพ', 'ท่าเรือ', '1', 'วังปริง');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ท่าแพ', 'ท่าเรือ', '2', 'ป่าเสม็ด');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ท่าแพ', 'ท่าเรือ', '3', 'ไร่ทอน');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ท่าแพ', 'ท่าเรือ', '4', 'แป-ระใต้');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ท่าแพ', 'ท่าเรือ', '5', 'ควนพัฒนา');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ท่าแพ', 'ท่าเรือ', '6', 'พรุต้นอ้อ');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('มะนัง', 'ปาล์มพัฒนา', '0', 'ปาล์มพัฒนา');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('มะนัง', 'ปาล์มพัฒนา', '1', 'ปาล์ม 1');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('มะนัง', 'ปาล์มพัฒนา', '2', 'ปาล์ม 3');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('มะนัง', 'ปาล์มพัฒนา', '3', 'ปาล์ม 4');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('มะนัง', 'ปาล์มพัฒนา', '4', 'ปาล์ม 2');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('มะนัง', 'ปาล์มพัฒนา', '5', 'มะนัง');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('มะนัง', 'ปาล์มพัฒนา', '6', 'ปากคอก');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('มะนัง', 'ปาล์มพัฒนา', '7', 'ปาล์ม 7');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('มะนัง', 'ปาล์มพัฒนา', '8', 'ปาล์มทองพัฒนา');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('มะนัง', 'ปาล์มพัฒนา', '9', 'ควนดินดำ');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('มะนัง', 'ปาล์มพัฒนา', '10', 'ไทรทอง');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('มะนัง', 'นิคมพัฒนา', '1', 'ผัง 6');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('มะนัง', 'นิคมพัฒนา', '2', 'ผัง 118');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('มะนัง', 'นิคมพัฒนา', '3', 'ผัง 7');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('มะนัง', 'นิคมพัฒนา', '4', 'ผัง 8');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('มะนัง', 'นิคมพัฒนา', '5', 'ผัง 50');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('มะนัง', 'นิคมพัฒนา', '6', 'วังพระเคียน');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('มะนัง', 'นิคมพัฒนา', '7', 'ผัง 13');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('มะนัง', 'นิคมพัฒนา', '8', 'ผัง 20');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('มะนัง', 'นิคมพัฒนา', '9', 'ก้าวใหม่พัฒนา');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ควนโดน', 'ควนโดน', '0', 'ควนโดน');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ควนโดน', 'ควนโดน', '2', 'สะพานเคียน');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ควนโดน', 'ควนโดน', '3', 'ถ้ำทะลุ');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ควนโดน', 'ควนโดน', '4', 'ควนโต๊ะเหลง');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ควนโดน', 'ควนโดน', '6', 'หัวสะพานเหล็ก');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ควนโดน', 'ควนโดน', '7', 'บูเก็ตยามู');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ควนโดน', 'ควนโดน', '8', 'ปลักใหญ่ใจดี');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ควนโดน', 'ควนโดน', '9', 'นาปริก');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ควนโดน', 'ควนโดน', '10', 'บาราเกตุ');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ควนโดน', 'ควนโดน', '1', 'ควนโดน');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ควนโดน', 'ควนโดน', '5', 'ดูสน');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ควนโดน', 'ควนสตอ', '1', 'โต๊ะสะ');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ควนโดน', 'ควนสตอ', '2', 'กุบังปะโหลด');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ควนโดน', 'ควนสตอ', '3', 'ควนยาหวา');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ควนโดน', 'ควนสตอ', '4', 'กลาง');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ควนโดน', 'ควนสตอ', '5', 'ทางงอ');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ควนโดน', 'ควนสตอ', '6', 'ปลักซิมปอ');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ควนโดน', 'ควนสตอ', '7', 'ควนสตอ');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ควนโดน', 'ควนสตอ', '8', 'หัวควน');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ควนโดน', 'ควนสตอ', '9', 'ควนไสน');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ควนโดน', 'ควนสตอ', '10', 'ทุ่งพัฒนา');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ควนโดน', 'ย่านซื่อ', '1', 'เขาพญาบังสา');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ควนโดน', 'ย่านซื่อ', '2', 'ย่านซื่อ');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ควนโดน', 'ย่านซื่อ', '3', 'เขาน้อย');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ควนโดน', 'ย่านซื่อ', '4', 'ห้วยคล้า');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ควนโดน', 'ย่านซื่อ', '7', 'ปากบาง');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ควนโดน', 'วังประจัน', '1', 'ทุ่งมะปรัง');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ควนโดน', 'วังประจัน', '2', 'เขานุ้ย');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ควนโดน', 'วังประจัน', '3', 'วังประจัน');
INSERT INTO villages (amphoe, tambon, moo, village_name) VALUES ('ควนโดน', 'วังประจัน', '4', 'วังประจันใต้');
