-- Flood EOC Session-based Management + Daily Reporting Cycle
-- Designed to extend existing eoc_sessions / eoc_teams without replacing them.

CREATE TABLE IF NOT EXISTS eoc_reporting_cycles (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  session_id BIGINT NOT NULL,
  report_date DATE NOT NULL,
  day_no INT NOT NULL,
  deadline_at DATETIME NOT NULL,
  cycle_status VARCHAR(40) NOT NULL DEFAULT 'open',
  closed_at DATETIME NULL,
  dashboard_generated_at DATETIME NULL,
  briefing_meeting_at DATETIME NULL,
  created_by BIGINT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uniq_cycle_session_date (session_id, report_date),
  KEY idx_cycle_status (cycle_status),
  KEY idx_cycle_deadline (deadline_at)
);

CREATE TABLE IF NOT EXISTS team_daily_inputs (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  session_id BIGINT NOT NULL,
  reporting_cycle_id BIGINT NOT NULL,
  report_date DATE NOT NULL,
  team_code VARCHAR(40) NOT NULL,
  team_name VARCHAR(160) NOT NULL,
  required_data_name VARCHAR(255) NOT NULL,
  input_status VARCHAR(40) NOT NULL DEFAULT 'Not Started',
  completed_percent INT NOT NULL DEFAULT 0,
  deadline_at DATETIME NOT NULL,
  submitted_at DATETIME NULL,
  is_late TINYINT(1) NOT NULL DEFAULT 0,
  submitted_by BIGINT NULL,
  reviewed_by BIGINT NULL,
  reviewed_at DATETIME NULL,
  review_status VARCHAR(40) NOT NULL DEFAULT 'Draft',
  approved_by BIGINT NULL,
  approved_at DATETIME NULL,
  missing_fields JSON NULL,
  remarks TEXT NULL,
  audit_log_id BIGINT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_team_inputs_cycle (reporting_cycle_id, team_code),
  KEY idx_team_inputs_status (input_status, review_status),
  KEY idx_team_inputs_late (is_late, submitted_at)
);

CREATE TABLE IF NOT EXISTS eoc_daily_summaries (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  session_id BIGINT NOT NULL,
  reporting_cycle_id BIGINT NOT NULL,
  report_date DATE NOT NULL,
  day_no INT NOT NULL,
  daily_status VARCHAR(40) NOT NULL,
  situation_summary TEXT NULL,
  affected_districts INT NOT NULL DEFAULT 0,
  affected_subdistricts INT NOT NULL DEFAULT 0,
  affected_villages INT NOT NULL DEFAULT 0,
  affected_households INT NOT NULL DEFAULT 0,
  affected_population INT NOT NULL DEFAULT 0,
  vulnerable_population INT NOT NULL DEFAULT 0,
  road_closed_count INT NOT NULL DEFAULT 0,
  shelter_open_count INT NOT NULL DEFAULT 0,
  health_facility_affected_count INT NOT NULL DEFAULT 0,
  help_request_count INT NOT NULL DEFAULT 0,
  mission_done_count INT NOT NULL DEFAULT 0,
  data_completeness_score DECIMAL(5,2) NOT NULL DEFAULT 0,
  submitted_team_count INT NOT NULL DEFAULT 0,
  missing_team_count INT NOT NULL DEFAULT 0,
  late_team_count INT NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uniq_daily_summary_cycle (reporting_cycle_id),
  KEY idx_daily_summary_date (session_id, report_date)
);

CREATE TABLE IF NOT EXISTS flood_reports (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  session_id BIGINT NOT NULL,
  reporting_cycle_id BIGINT NOT NULL,
  report_date DATE NOT NULL,
  district VARCHAR(120) NOT NULL,
  subdistrict VARCHAR(120) NULL,
  village VARCHAR(120) NULL,
  latitude DECIMAL(10,7) NULL,
  longitude DECIMAL(10,7) NULL,
  flood_type VARCHAR(80) NOT NULL,
  water_level_cm INT NULL,
  water_trend VARCHAR(40) NULL,
  severity_level VARCHAR(40) NULL,
  affected_households INT NOT NULL DEFAULT 0,
  affected_population INT NOT NULL DEFAULT 0,
  vulnerable_population INT NOT NULL DEFAULT 0,
  road_affected TINYINT(1) NOT NULL DEFAULT 0,
  health_facility_affected TINYINT(1) NOT NULL DEFAULT 0,
  verification_status VARCHAR(40) NOT NULL DEFAULT 'Draft',
  public_visibility TINYINT(1) NOT NULL DEFAULT 0,
  publish_status VARCHAR(40) NOT NULL DEFAULT 'internal',
  reported_by_team VARCHAR(40) NOT NULL,
  reported_by BIGINT NULL,
  submitted_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_flood_reports_cycle (reporting_cycle_id),
  KEY idx_flood_reports_area (district, subdistrict, village),
  KEY idx_flood_reports_publish (public_visibility, publish_status)
);

CREATE TABLE IF NOT EXISTS logistics_reports (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  session_id BIGINT NOT NULL,
  reporting_cycle_id BIGINT NOT NULL,
  report_date DATE NOT NULL,
  resource_type VARCHAR(80) NOT NULL,
  resource_name VARCHAR(160) NOT NULL,
  quantity_total INT NOT NULL DEFAULT 0,
  quantity_dispatched INT NOT NULL DEFAULT 0,
  quantity_remaining INT NOT NULL DEFAULT 0,
  destination VARCHAR(255) NULL,
  receiving_agency VARCHAR(160) NULL,
  delivery_status VARCHAR(80) NULL,
  transport_issue TEXT NULL,
  evidence_file VARCHAR(255) NULL,
  submitted_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_logistics_cycle (reporting_cycle_id, resource_type)
);

CREATE TABLE IF NOT EXISTS it_status_reports (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  session_id BIGINT NOT NULL,
  reporting_cycle_id BIGINT NOT NULL,
  report_date DATE NOT NULL,
  agency VARCHAR(160) NOT NULL,
  district VARCHAR(120) NULL,
  device_type VARCHAR(80) NOT NULL,
  total_devices INT NOT NULL DEFAULT 0,
  working_devices INT NOT NULL DEFAULT 0,
  damaged_devices INT NOT NULL DEFAULT 0,
  internet_status VARCHAR(80) NULL,
  dashboard_status VARCHAR(80) NULL,
  affected_by_flood TINYINT(1) NOT NULL DEFAULT 0,
  issue_description TEXT NULL,
  support_needed TEXT NULL,
  submitted_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_it_reports_cycle (reporting_cycle_id, device_type)
);

CREATE TABLE IF NOT EXISTS health_reports (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  session_id BIGINT NOT NULL,
  reporting_cycle_id BIGINT NOT NULL,
  report_date DATE NOT NULL,
  facility_name VARCHAR(160) NOT NULL,
  district VARCHAR(120) NULL,
  service_status VARCHAR(80) NULL,
  emergency_patients INT NOT NULL DEFAULT 0,
  flood_related_disease_cases INT NOT NULL DEFAULT 0,
  vulnerable_followup_count INT NOT NULL DEFAULT 0,
  medical_supply_needed TEXT NULL,
  mobile_medical_team_status VARCHAR(120) NULL,
  issues TEXT NULL,
  submitted_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_health_reports_cycle (reporting_cycle_id, district)
);

CREATE TABLE IF NOT EXISTS shelter_reports (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  session_id BIGINT NOT NULL,
  reporting_cycle_id BIGINT NOT NULL,
  report_date DATE NOT NULL,
  shelter_name VARCHAR(160) NOT NULL,
  district VARCHAR(120) NULL,
  capacity INT NOT NULL DEFAULT 0,
  current_occupancy INT NOT NULL DEFAULT 0,
  available_capacity INT NOT NULL DEFAULT 0,
  elderly_count INT NOT NULL DEFAULT 0,
  children_count INT NOT NULL DEFAULT 0,
  pregnant_count INT NOT NULL DEFAULT 0,
  disabled_count INT NOT NULL DEFAULT 0,
  food_status VARCHAR(80) NULL,
  water_status VARCHAR(80) NULL,
  toilet_status VARCHAR(80) NULL,
  medical_point_status VARCHAR(80) NULL,
  support_needed TEXT NULL,
  submitted_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_shelter_reports_cycle (reporting_cycle_id, district)
);

CREATE TABLE IF NOT EXISTS missions (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  session_id BIGINT NOT NULL,
  reporting_cycle_id BIGINT NULL,
  report_date DATE NULL,
  mission_code VARCHAR(60) NOT NULL,
  mission_type VARCHAR(120) NOT NULL,
  mission_name VARCHAR(255) NOT NULL,
  area VARCHAR(255) NULL,
  assigned_team VARCHAR(160) NULL,
  responsible_agency VARCHAR(160) NULL,
  priority VARCHAR(40) NOT NULL DEFAULT 'ปานกลาง',
  due_at DATETIME NULL,
  status VARCHAR(40) NOT NULL DEFAULT 'intake',
  progress_percent INT NOT NULL DEFAULT 0,
  evidence_file VARCHAR(255) NULL,
  ordered_by BIGINT NULL,
  responsible_person VARCHAR(160) NULL,
  remarks TEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uniq_mission_code (mission_code),
  KEY idx_missions_session_status (session_id, status),
  KEY idx_missions_due (due_at)
);

CREATE TABLE IF NOT EXISTS meeting_notes (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  session_id BIGINT NOT NULL,
  reporting_cycle_id BIGINT NOT NULL,
  meeting_date DATE NOT NULL,
  meeting_time TIME NOT NULL,
  chairperson VARCHAR(160) NULL,
  attendees JSON NULL,
  agenda TEXT NULL,
  situation_summary TEXT NULL,
  key_issues JSON NULL,
  decisions JSON NULL,
  orders TEXT NULL,
  responsible_team VARCHAR(160) NULL,
  due_date DATE NULL,
  followup_status VARCHAR(80) NULL,
  next_meeting_datetime DATETIME NULL,
  attachment VARCHAR(255) NULL,
  created_by BIGINT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_meeting_session_date (session_id, meeting_date)
);

CREATE TABLE IF NOT EXISTS decision_logs (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  session_id BIGINT NOT NULL,
  reporting_cycle_id BIGINT NULL,
  decision_datetime DATETIME NOT NULL,
  decision_maker VARCHAR(160) NULL,
  issue TEXT NOT NULL,
  supporting_data TEXT NULL,
  decision TEXT NOT NULL,
  assigned_team VARCHAR(160) NULL,
  followup_due DATETIME NULL,
  status VARCHAR(80) NOT NULL DEFAULT 'รอติดตามผล',
  attachment VARCHAR(255) NULL,
  linked_mission_id BIGINT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_decisions_session (session_id, decision_datetime),
  KEY idx_decisions_status (status)
);
