CREATE TABLE IF NOT EXISTS eoc_team_reports (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  eoc_session_id BIGINT NOT NULL,
  session_team_id INT NOT NULL,
  team_code VARCHAR(50) NOT NULL,
  report_date DATETIME NOT NULL,
  report_type VARCHAR(80) NOT NULL DEFAULT 'periodic',
  title VARCHAR(255) NOT NULL,
  status ENUM('draft','submitted','approved','returned') NOT NULL DEFAULT 'draft',
  payload JSON NOT NULL,
  created_by INT NOT NULL,
  updated_by INT NOT NULL,
  submitted_by INT NULL,
  submitted_at DATETIME NULL,
  reviewed_by INT NULL,
  reviewed_at DATETIME NULL,
  review_comment TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_team_reports_session FOREIGN KEY (eoc_session_id) REFERENCES eoc_sessions(id) ON DELETE CASCADE,
  CONSTRAINT fk_team_reports_session_team FOREIGN KEY (session_team_id) REFERENCES eoc_session_teams(id) ON DELETE CASCADE,
  CONSTRAINT fk_team_reports_created_by FOREIGN KEY (created_by) REFERENCES officer(id),
  KEY idx_team_reports_session_team (eoc_session_id, session_team_id, report_date),
  KEY idx_team_reports_team_status (team_code, status),
  KEY idx_team_reports_updated (updated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
